/*
 * Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
 * 
 * On Thu Nov 17 03:27:03 PST 2022
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkAudioPipeline_h__
#define __mkAudioPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMultiplier.h"


/* Class declaration for the mkAudioPipeline module */
class MOD_mkAudioPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_adjust_bin;
  MOD_Reg<tUInt8> INST_adjust_done;
  MOD_Reg<tUInt8> INST_adjust_i;
  MOD_Reg<tUWide> INST_adjust_in_latch;
  MOD_Reg<tUInt32> INST_adjust_inphases_0;
  MOD_Reg<tUInt32> INST_adjust_inphases_1;
  MOD_Reg<tUInt32> INST_adjust_inphases_2;
  MOD_Reg<tUInt32> INST_adjust_inphases_3;
  MOD_Reg<tUInt32> INST_adjust_inphases_4;
  MOD_Reg<tUInt32> INST_adjust_inphases_5;
  MOD_Reg<tUInt32> INST_adjust_inphases_6;
  MOD_Reg<tUInt32> INST_adjust_inphases_7;
  MOD_Reg<tUWide> INST_adjust_out_latch;
  MOD_Reg<tUInt32> INST_adjust_outphases_0;
  MOD_Reg<tUInt32> INST_adjust_outphases_1;
  MOD_Reg<tUInt32> INST_adjust_outphases_2;
  MOD_Reg<tUInt32> INST_adjust_outphases_3;
  MOD_Reg<tUInt32> INST_adjust_outphases_4;
  MOD_Reg<tUInt32> INST_adjust_outphases_5;
  MOD_Reg<tUInt32> INST_adjust_outphases_6;
  MOD_Reg<tUInt32> INST_adjust_outphases_7;
  MOD_Fifo<tUWide> INST_adjust_outputFIFO;
  MOD_Reg<tUInt8> INST_chunker_index;
  MOD_Reg<tUInt8> INST_chunker_index_double_write_error;
  MOD_Fifo<tUInt32> INST_chunker_infifo;
  MOD_Fifo<tUInt32> INST_chunker_outfifo;
  MOD_Reg<tUInt32> INST_chunker_pending;
  MOD_Reg<tUInt8> INST_chunker_pending_double_write_error;
  MOD_Fifo<tUWide> INST_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_fft_fft_outputFIFO;
  MOD_Reg<tUWide> INST_fft_fft_stage_data_0;
  MOD_Reg<tUInt8> INST_fft_fft_stage_data_0_double_write_error;
  MOD_Reg<tUWide> INST_fft_fft_stage_data_1;
  MOD_Reg<tUInt8> INST_fft_fft_stage_data_1_double_write_error;
  MOD_Reg<tUWide> INST_fft_fft_stage_data_2;
  MOD_Reg<tUInt8> INST_fft_fft_stage_data_2_double_write_error;
  MOD_Reg<tUWide> INST_fft_fft_stage_data_3;
  MOD_Reg<tUInt8> INST_fft_fft_stage_data_3_double_write_error;
  MOD_Fifo<tUInt32> INST_fir_infifo;
  MOD_mkMultiplier INST_fir_m_0;
  MOD_mkMultiplier INST_fir_m_1;
  MOD_mkMultiplier INST_fir_m_2;
  MOD_mkMultiplier INST_fir_m_3;
  MOD_mkMultiplier INST_fir_m_4;
  MOD_mkMultiplier INST_fir_m_5;
  MOD_mkMultiplier INST_fir_m_6;
  MOD_mkMultiplier INST_fir_m_7;
  MOD_mkMultiplier INST_fir_m_8;
  MOD_Fifo<tUInt32> INST_fir_outfifo;
  MOD_Reg<tUInt32> INST_fir_r_0;
  MOD_Reg<tUInt32> INST_fir_r_1;
  MOD_Reg<tUInt32> INST_fir_r_2;
  MOD_Reg<tUInt32> INST_fir_r_3;
  MOD_Reg<tUInt32> INST_fir_r_4;
  MOD_Reg<tUInt32> INST_fir_r_5;
  MOD_Reg<tUInt32> INST_fir_r_6;
  MOD_Reg<tUInt32> INST_fir_r_7;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_0_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_0_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_0_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_0_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_0_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_0_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_0_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_1_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_1_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_1_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_1_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_1_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_1_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_1_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_2_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_2_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_2_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_2_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_2_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_2_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_2_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_3_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_3_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_3_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_3_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_3_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_3_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_3_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_4_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_4_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_4_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_4_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_4_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_4_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_4_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_5_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_5_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_5_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_5_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_5_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_5_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_5_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_6_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_6_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_6_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_6_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_6_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_6_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_6_rel;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_7_idle;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_7_img;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_7_infifo;
  MOD_Reg<tUInt8> INST_fromMp_cordFromMp_7_iter;
  MOD_Fifo<tUInt64> INST_fromMp_cordFromMp_7_outfifo;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_7_phase;
  MOD_Reg<tUInt32> INST_fromMp_cordFromMp_7_rel;
  MOD_Fifo<tUWide> INST_fromMp_outfifo;
  MOD_Fifo<tUWide> INST_ifft_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_ifft_fft_fft_outputFIFO;
  MOD_Reg<tUWide> INST_ifft_fft_fft_stage_data_0;
  MOD_Reg<tUInt8> INST_ifft_fft_fft_stage_data_0_double_write_error;
  MOD_Reg<tUWide> INST_ifft_fft_fft_stage_data_1;
  MOD_Reg<tUInt8> INST_ifft_fft_fft_stage_data_1_double_write_error;
  MOD_Reg<tUWide> INST_ifft_fft_fft_stage_data_2;
  MOD_Reg<tUInt8> INST_ifft_fft_fft_stage_data_2_double_write_error;
  MOD_Reg<tUWide> INST_ifft_fft_fft_stage_data_3;
  MOD_Reg<tUInt8> INST_ifft_fft_fft_stage_data_3_double_write_error;
  MOD_Fifo<tUWide> INST_ifft_outfifo;
  MOD_Fifo<tUWide> INST_overlayer_infifo;
  MOD_Fifo<tUInt32> INST_overlayer_outfifo;
  MOD_Reg<tUWide> INST_overlayer_window;
  MOD_Fifo<tUInt32> INST_oversample_infifo;
  MOD_Fifo<tUWide> INST_oversample_outfifo;
  MOD_Reg<tUWide> INST_oversample_window;
  MOD_Reg<tUInt8> INST_splitter_index;
  MOD_Reg<tUInt8> INST_splitter_index_double_write_error;
  MOD_Fifo<tUInt32> INST_splitter_infifo;
  MOD_Fifo<tUInt32> INST_splitter_outfifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_0_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_0_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_0_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_0_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_0_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_0_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_0_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_1_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_1_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_1_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_1_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_1_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_1_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_1_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_2_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_2_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_2_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_2_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_2_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_2_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_2_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_3_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_3_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_3_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_3_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_3_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_3_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_3_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_4_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_4_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_4_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_4_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_4_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_4_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_4_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_5_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_5_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_5_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_5_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_5_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_5_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_5_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_6_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_6_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_6_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_6_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_6_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_6_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_6_rel;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_7_idle;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_7_img;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_7_infifo;
  MOD_Reg<tUInt8> INST_toMp_cordToMp_7_iter;
  MOD_Fifo<tUInt64> INST_toMp_cordToMp_7_outfifo;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_7_phase;
  MOD_Reg<tUInt32> INST_toMp_cordToMp_7_rel;
  MOD_Fifo<tUWide> INST_toMp_outfifo;
 
 /* Constructor */
 public:
  MOD_mkAudioPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_putSampleInput;
  tUInt8 PORT_EN_getSampleOutput;
  tUInt32 PORT_putSampleInput_in;
  tUInt8 PORT_RDY_putSampleInput;
  tUInt32 PORT_getSampleOutput;
  tUInt8 PORT_RDY_getSampleOutput;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_getSampleOutput;
  tUInt8 DEF_WILL_FIRE_putSampleInput;
  tUInt8 DEF_WILL_FIRE_RL_overlayer_to_splitter;
  tUInt8 DEF_CAN_FIRE_RL_overlayer_to_splitter;
  tUInt8 DEF_WILL_FIRE_RL_ifft_to_overlayer;
  tUInt8 DEF_CAN_FIRE_RL_ifft_to_overlayer;
  tUInt8 DEF_WILL_FIRE_RL_frommp_to_ifft;
  tUInt8 DEF_CAN_FIRE_RL_frommp_to_ifft;
  tUInt8 DEF_WILL_FIRE_RL_adjust_to_frommp;
  tUInt8 DEF_CAN_FIRE_RL_adjust_to_frommp;
  tUInt8 DEF_WILL_FIRE_RL_tomp_to_adjust;
  tUInt8 DEF_CAN_FIRE_RL_tomp_to_adjust;
  tUInt8 DEF_WILL_FIRE_RL_fft_to_tomp;
  tUInt8 DEF_CAN_FIRE_RL_fft_to_tomp;
  tUInt8 DEF_WILL_FIRE_RL_oversample_to_fft;
  tUInt8 DEF_CAN_FIRE_RL_oversample_to_fft;
  tUInt8 DEF_WILL_FIRE_RL_chunker_to_oversample;
  tUInt8 DEF_CAN_FIRE_RL_chunker_to_oversample;
  tUInt8 DEF_WILL_FIRE_RL_fir_to_chunker;
  tUInt8 DEF_CAN_FIRE_RL_fir_to_chunker;
  tUInt8 DEF_WILL_FIRE_RL_splitter_iterate;
  tUInt8 DEF_CAN_FIRE_RL_splitter_iterate;
  tUInt8 DEF_WILL_FIRE_RL_overlayer_shiftout;
  tUInt8 DEF_CAN_FIRE_RL_overlayer_shiftout;
  tUInt8 DEF_WILL_FIRE_RL_ifft_inversify;
  tUInt8 DEF_CAN_FIRE_RL_ifft_inversify;
  tUInt8 DEF_WILL_FIRE_RL_ifft_fft_fft_comb_fft;
  tUInt8 DEF_CAN_FIRE_RL_ifft_fft_fft_comb_fft;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_get_data;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_get_data;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_7_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_7_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_7_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_7_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_6_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_6_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_6_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_6_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_5_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_5_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_5_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_5_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_4_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_4_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_4_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_4_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_3_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_3_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_3_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_3_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_2_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_2_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_2_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_2_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_1_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_1_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_1_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_1_start;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_0_iterate;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_0_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fromMp_cordFromMp_0_start;
  tUInt8 DEF_CAN_FIRE_RL_fromMp_cordFromMp_0_start;
  tUInt8 DEF_WILL_FIRE_RL_adjust_loop_end;
  tUInt8 DEF_CAN_FIRE_RL_adjust_loop_end;
  tUInt8 DEF_WILL_FIRE_RL_adjust_loop;
  tUInt8 DEF_CAN_FIRE_RL_adjust_loop;
  tUInt8 DEF_WILL_FIRE_RL_toMp_get_data;
  tUInt8 DEF_CAN_FIRE_RL_toMp_get_data;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_7_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_7_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_7_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_7_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_6_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_6_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_6_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_6_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_5_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_5_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_5_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_5_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_4_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_4_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_4_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_4_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_3_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_3_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_3_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_3_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_2_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_2_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_2_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_2_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_1_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_1_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_1_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_1_start;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_0_iterate;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_0_iterate;
  tUInt8 DEF_WILL_FIRE_RL_toMp_cordToMp_0_start;
  tUInt8 DEF_CAN_FIRE_RL_toMp_cordToMp_0_start;
  tUInt8 DEF_WILL_FIRE_RL_fft_fft_comb_fft;
  tUInt8 DEF_CAN_FIRE_RL_fft_fft_comb_fft;
  tUInt8 DEF_WILL_FIRE_RL_oversample_shiftin;
  tUInt8 DEF_CAN_FIRE_RL_oversample_shiftin;
  tUInt8 DEF_WILL_FIRE_RL_chunker_iterate;
  tUInt8 DEF_CAN_FIRE_RL_chunker_iterate;
  tUInt8 DEF_WILL_FIRE_RL_fir_add;
  tUInt8 DEF_CAN_FIRE_RL_fir_add;
  tUInt8 DEF_WILL_FIRE_RL_fir_mult;
  tUInt8 DEF_CAN_FIRE_RL_fir_mult;
  tUInt8 DEF_CAN_FIRE_getSampleOutput;
  tUInt8 DEF_CAN_FIRE_putSampleInput;
  tUInt8 DEF_x__h372660;
  tUInt8 DEF_chunker_index__h7399;
  tUWide DEF_ifft_fft_fft_stage_data_3___d2968;
  tUWide DEF_fft_fft_stage_data_3___d99;
  tUInt64 DEF_toMp_cordToMp_7_infifo_first____d2023;
  tUInt64 DEF_toMp_cordToMp_6_infifo_first____d1910;
  tUInt64 DEF_toMp_cordToMp_5_infifo_first____d1797;
  tUInt64 DEF_toMp_cordToMp_4_infifo_first____d1684;
  tUInt64 DEF_toMp_cordToMp_3_infifo_first____d1571;
  tUInt64 DEF_toMp_cordToMp_2_infifo_first____d1458;
  tUInt64 DEF_toMp_cordToMp_1_infifo_first____d1345;
  tUInt64 DEF_toMp_cordToMp_0_infifo_first____d1231;
  tUInt8 DEF_x__h415992;
  tUInt8 DEF_x__h410691;
  tUInt8 DEF_x__h405390;
  tUInt8 DEF_x__h400089;
  tUInt8 DEF_x__h394788;
  tUInt8 DEF_x__h389487;
  tUInt8 DEF_x__h384186;
  tUInt8 DEF_x__h378885;
  tUInt8 DEF_x__h362716;
  tUInt8 DEF_x__h357481;
  tUInt8 DEF_x__h352246;
  tUInt8 DEF_x__h347011;
  tUInt8 DEF_x__h341776;
  tUInt8 DEF_x__h336541;
  tUInt8 DEF_x__h331306;
  tUInt8 DEF_x__h326068;
  tUInt8 DEF_ifft_fft_fft_inputFIFO_notEmpty____d2961;
  tUInt8 DEF_fft_fft_inputFIFO_notEmpty____d92;
  tUInt32 DEF_toMp_cordToMp_7_infifo_first__023_BITS_63_TO_32___d2045;
  tUInt32 DEF_toMp_cordToMp_7_infifo_first__023_BITS_31_TO_0___d2029;
  tUInt32 DEF_toMp_cordToMp_6_infifo_first__910_BITS_63_TO_32___d1932;
  tUInt32 DEF_toMp_cordToMp_6_infifo_first__910_BITS_31_TO_0___d1916;
  tUInt32 DEF_toMp_cordToMp_5_infifo_first__797_BITS_63_TO_32___d1819;
  tUInt32 DEF_toMp_cordToMp_5_infifo_first__797_BITS_31_TO_0___d1803;
  tUInt32 DEF_toMp_cordToMp_4_infifo_first__684_BITS_63_TO_32___d1706;
  tUInt32 DEF_toMp_cordToMp_4_infifo_first__684_BITS_31_TO_0___d1690;
  tUInt32 DEF_toMp_cordToMp_3_infifo_first__571_BITS_63_TO_32___d1593;
  tUInt32 DEF_toMp_cordToMp_3_infifo_first__571_BITS_31_TO_0___d1577;
  tUInt32 DEF_toMp_cordToMp_2_infifo_first__458_BITS_63_TO_32___d1480;
  tUInt32 DEF_toMp_cordToMp_2_infifo_first__458_BITS_31_TO_0___d1464;
  tUInt32 DEF_toMp_cordToMp_1_infifo_first__345_BITS_63_TO_32___d1367;
  tUInt32 DEF_toMp_cordToMp_1_infifo_first__345_BITS_31_TO_0___d1351;
  tUInt32 DEF_toMp_cordToMp_0_infifo_first__231_BITS_63_TO_32___d1253;
  tUInt32 DEF_toMp_cordToMp_0_infifo_first__231_BITS_31_TO_0___d1237;
  tUInt32 DEF_x_first_rel_i__h361498;
  tUInt32 DEF_x_first_rel_f__h361499;
  tUInt32 DEF_x_first_img_i__h361522;
  tUInt32 DEF_x_first_img_f__h361523;
  tUInt32 DEF_x_first_rel_i__h356263;
  tUInt32 DEF_x_first_rel_f__h356264;
  tUInt32 DEF_x_first_img_i__h356287;
  tUInt32 DEF_x_first_img_f__h356288;
  tUInt32 DEF_x_first_rel_i__h351028;
  tUInt32 DEF_x_first_rel_f__h351029;
  tUInt32 DEF_x_first_img_i__h351052;
  tUInt32 DEF_x_first_img_f__h351053;
  tUInt32 DEF_x_first_rel_i__h345793;
  tUInt32 DEF_x_first_rel_f__h345794;
  tUInt32 DEF_x_first_img_i__h345817;
  tUInt32 DEF_x_first_img_f__h345818;
  tUInt32 DEF_x_first_rel_i__h340558;
  tUInt32 DEF_x_first_rel_f__h340559;
  tUInt32 DEF_x_first_img_i__h340582;
  tUInt32 DEF_x_first_img_f__h340583;
  tUInt32 DEF_x_first_rel_i__h335323;
  tUInt32 DEF_x_first_rel_f__h335324;
  tUInt32 DEF_x_first_img_i__h335347;
  tUInt32 DEF_x_first_img_f__h335348;
  tUInt32 DEF_x_first_rel_i__h330088;
  tUInt32 DEF_x_first_rel_f__h330089;
  tUInt32 DEF_x_first_img_i__h330112;
  tUInt32 DEF_x_first_img_f__h330113;
  tUInt32 DEF_x_first_rel_i__h324775;
  tUInt32 DEF_x_first_rel_f__h324776;
  tUInt32 DEF_x_first_img_i__h324802;
  tUInt32 DEF_x_first_img_f__h324803;
  tUInt32 DEF_i___1_i__h361618;
  tUInt32 DEF_x__h361616;
  tUInt32 DEF_i___1_f__h361619;
  tUInt32 DEF_r___1_i__h361586;
  tUInt32 DEF_x__h361584;
  tUInt32 DEF_r___1_f__h361587;
  tUInt32 DEF_i___1_i__h356383;
  tUInt32 DEF_x__h356381;
  tUInt32 DEF_i___1_f__h356384;
  tUInt32 DEF_r___1_i__h356351;
  tUInt32 DEF_x__h356349;
  tUInt32 DEF_r___1_f__h356352;
  tUInt32 DEF_i___1_i__h351148;
  tUInt32 DEF_x__h351146;
  tUInt32 DEF_i___1_f__h351149;
  tUInt32 DEF_r___1_i__h351116;
  tUInt32 DEF_x__h351114;
  tUInt32 DEF_r___1_f__h351117;
  tUInt32 DEF_i___1_i__h345913;
  tUInt32 DEF_x__h345911;
  tUInt32 DEF_i___1_f__h345914;
  tUInt32 DEF_r___1_i__h345881;
  tUInt32 DEF_x__h345879;
  tUInt32 DEF_r___1_f__h345882;
  tUInt32 DEF_i___1_i__h340678;
  tUInt32 DEF_x__h340676;
  tUInt32 DEF_i___1_f__h340679;
  tUInt32 DEF_r___1_i__h340646;
  tUInt32 DEF_x__h340644;
  tUInt32 DEF_r___1_f__h340647;
  tUInt32 DEF_i___1_i__h335443;
  tUInt32 DEF_x__h335441;
  tUInt32 DEF_i___1_f__h335444;
  tUInt32 DEF_r___1_i__h335411;
  tUInt32 DEF_x__h335409;
  tUInt32 DEF_r___1_f__h335412;
  tUInt32 DEF_i___1_i__h330208;
  tUInt32 DEF_x__h330206;
  tUInt32 DEF_i___1_f__h330209;
  tUInt32 DEF_r___1_i__h330176;
  tUInt32 DEF_x__h330174;
  tUInt32 DEF_r___1_f__h330177;
  tUInt32 DEF_i___1_i__h324916;
  tUInt32 DEF_x__h324914;
  tUInt32 DEF_i___1_f__h324917;
  tUInt32 DEF_r___1_i__h324884;
  tUInt32 DEF_x__h324882;
  tUInt32 DEF_r___1_f__h324885;
  tUInt8 DEF_ifft_fft_fft_stage_data_3_968_BIT_512___d2969;
  tUInt8 DEF_fft_fft_stage_data_3_9_BIT_512___d100;
  tUInt8 DEF_toMp_cordToMp_7_infifo_first__023_BIT_63___d2024;
  tUInt8 DEF_toMp_cordToMp_6_infifo_first__910_BIT_63___d1911;
  tUInt8 DEF_toMp_cordToMp_5_infifo_first__797_BIT_63___d1798;
  tUInt8 DEF_toMp_cordToMp_4_infifo_first__684_BIT_63___d1685;
  tUInt8 DEF_toMp_cordToMp_3_infifo_first__571_BIT_63___d1572;
  tUInt8 DEF_toMp_cordToMp_2_infifo_first__458_BIT_63___d1459;
  tUInt8 DEF_toMp_cordToMp_1_infifo_first__345_BIT_63___d1346;
  tUInt8 DEF_toMp_cordToMp_0_infifo_first__231_BIT_63___d1232;
  tUInt8 DEF_toMp_cordToMp_7_infifo_first__023_BIT_63_024_A_ETC___d2027;
  tUInt8 DEF_toMp_cordToMp_6_infifo_first__910_BIT_63_911_A_ETC___d1914;
  tUInt8 DEF_toMp_cordToMp_5_infifo_first__797_BIT_63_798_A_ETC___d1801;
  tUInt8 DEF_toMp_cordToMp_4_infifo_first__684_BIT_63_685_A_ETC___d1688;
  tUInt8 DEF_toMp_cordToMp_3_infifo_first__571_BIT_63_572_A_ETC___d1575;
  tUInt8 DEF_toMp_cordToMp_2_infifo_first__458_BIT_63_459_A_ETC___d1462;
  tUInt8 DEF_toMp_cordToMp_1_infifo_first__345_BIT_63_346_A_ETC___d1349;
  tUInt8 DEF_toMp_cordToMp_0_infifo_first__231_BIT_63_232_A_ETC___d1235;
  tUInt32 DEF__theResult___fst_f__h361621;
  tUInt32 DEF__theResult___fst_i__h361620;
  tUInt32 DEF__theResult___snd_fst_f__h361589;
  tUInt32 DEF__theResult___snd_fst_i__h361588;
  tUInt32 DEF__theResult___fst_f__h356386;
  tUInt32 DEF__theResult___fst_i__h356385;
  tUInt32 DEF__theResult___snd_fst_f__h356354;
  tUInt32 DEF__theResult___snd_fst_i__h356353;
  tUInt32 DEF__theResult___fst_f__h351151;
  tUInt32 DEF__theResult___fst_i__h351150;
  tUInt32 DEF__theResult___snd_fst_f__h351119;
  tUInt32 DEF__theResult___snd_fst_i__h351118;
  tUInt32 DEF__theResult___fst_f__h345916;
  tUInt32 DEF__theResult___fst_i__h345915;
  tUInt32 DEF__theResult___snd_fst_f__h345884;
  tUInt32 DEF__theResult___snd_fst_i__h345883;
  tUInt32 DEF__theResult___fst_f__h340681;
  tUInt32 DEF__theResult___fst_i__h340680;
  tUInt32 DEF__theResult___snd_fst_f__h340649;
  tUInt32 DEF__theResult___snd_fst_i__h340648;
  tUInt32 DEF__theResult___fst_f__h335446;
  tUInt32 DEF__theResult___fst_i__h335445;
  tUInt32 DEF__theResult___snd_fst_f__h335414;
  tUInt32 DEF__theResult___snd_fst_i__h335413;
  tUInt32 DEF__theResult___fst_f__h330211;
  tUInt32 DEF__theResult___fst_i__h330210;
  tUInt32 DEF__theResult___snd_fst_f__h330179;
  tUInt32 DEF__theResult___snd_fst_i__h330178;
  tUInt32 DEF__theResult___fst_f__h324919;
  tUInt32 DEF__theResult___fst_i__h324918;
  tUInt32 DEF__theResult___snd_fst_f__h324887;
  tUInt32 DEF__theResult___snd_fst_i__h324886;
  tUInt8 DEF_IF_toMp_cordToMp_7_infifo_first__023_BIT_63_02_ETC___d2055;
  tUInt8 DEF_IF_toMp_cordToMp_7_infifo_first__023_BIT_63_02_ETC___d2050;
  tUInt8 DEF_IF_toMp_cordToMp_7_infifo_first__023_BIT_63_02_ETC___d2042;
  tUInt8 DEF_IF_toMp_cordToMp_7_infifo_first__023_BIT_63_02_ETC___d2035;
  tUInt8 DEF_IF_toMp_cordToMp_6_infifo_first__910_BIT_63_91_ETC___d1942;
  tUInt8 DEF_IF_toMp_cordToMp_6_infifo_first__910_BIT_63_91_ETC___d1937;
  tUInt8 DEF_IF_toMp_cordToMp_6_infifo_first__910_BIT_63_91_ETC___d1929;
  tUInt8 DEF_IF_toMp_cordToMp_6_infifo_first__910_BIT_63_91_ETC___d1922;
  tUInt8 DEF_IF_toMp_cordToMp_5_infifo_first__797_BIT_63_79_ETC___d1829;
  tUInt8 DEF_IF_toMp_cordToMp_5_infifo_first__797_BIT_63_79_ETC___d1824;
  tUInt8 DEF_IF_toMp_cordToMp_5_infifo_first__797_BIT_63_79_ETC___d1816;
  tUInt8 DEF_IF_toMp_cordToMp_5_infifo_first__797_BIT_63_79_ETC___d1809;
  tUInt8 DEF_IF_toMp_cordToMp_4_infifo_first__684_BIT_63_68_ETC___d1716;
  tUInt8 DEF_IF_toMp_cordToMp_4_infifo_first__684_BIT_63_68_ETC___d1711;
  tUInt8 DEF_IF_toMp_cordToMp_4_infifo_first__684_BIT_63_68_ETC___d1703;
  tUInt8 DEF_IF_toMp_cordToMp_4_infifo_first__684_BIT_63_68_ETC___d1696;
  tUInt8 DEF_IF_toMp_cordToMp_3_infifo_first__571_BIT_63_57_ETC___d1603;
  tUInt8 DEF_IF_toMp_cordToMp_3_infifo_first__571_BIT_63_57_ETC___d1598;
  tUInt8 DEF_IF_toMp_cordToMp_3_infifo_first__571_BIT_63_57_ETC___d1590;
  tUInt8 DEF_IF_toMp_cordToMp_3_infifo_first__571_BIT_63_57_ETC___d1583;
  tUInt8 DEF_IF_toMp_cordToMp_2_infifo_first__458_BIT_63_45_ETC___d1490;
  tUInt8 DEF_IF_toMp_cordToMp_2_infifo_first__458_BIT_63_45_ETC___d1485;
  tUInt8 DEF_IF_toMp_cordToMp_2_infifo_first__458_BIT_63_45_ETC___d1477;
  tUInt8 DEF_IF_toMp_cordToMp_2_infifo_first__458_BIT_63_45_ETC___d1470;
  tUInt8 DEF_IF_toMp_cordToMp_1_infifo_first__345_BIT_63_34_ETC___d1377;
  tUInt8 DEF_IF_toMp_cordToMp_1_infifo_first__345_BIT_63_34_ETC___d1372;
  tUInt8 DEF_IF_toMp_cordToMp_1_infifo_first__345_BIT_63_34_ETC___d1364;
  tUInt8 DEF_IF_toMp_cordToMp_1_infifo_first__345_BIT_63_34_ETC___d1357;
  tUInt8 DEF_IF_toMp_cordToMp_0_infifo_first__231_BIT_63_23_ETC___d1263;
  tUInt8 DEF_IF_toMp_cordToMp_0_infifo_first__231_BIT_63_23_ETC___d1258;
  tUInt8 DEF_IF_toMp_cordToMp_0_infifo_first__231_BIT_63_23_ETC___d1250;
  tUInt8 DEF_IF_toMp_cordToMp_0_infifo_first__231_BIT_63_23_ETC___d1243;
  tUInt8 DEF_fromMp_cordFromMp_7_iter_906_EQ_15___d2907;
  tUInt8 DEF_fromMp_cordFromMp_6_iter_826_EQ_15___d2827;
  tUInt8 DEF_fromMp_cordFromMp_5_iter_746_EQ_15___d2747;
  tUInt8 DEF_fromMp_cordFromMp_4_iter_666_EQ_15___d2667;
  tUInt8 DEF_fromMp_cordFromMp_3_iter_586_EQ_15___d2587;
  tUInt8 DEF_fromMp_cordFromMp_2_iter_506_EQ_15___d2507;
  tUInt8 DEF_fromMp_cordFromMp_1_iter_426_EQ_15___d2427;
  tUInt8 DEF_fromMp_cordFromMp_0_iter_346_EQ_15___d2347;
  tUInt8 DEF_toMp_cordToMp_7_iter_073_EQ_15___d2074;
  tUInt8 DEF_toMp_cordToMp_6_iter_960_EQ_15___d1961;
  tUInt8 DEF_toMp_cordToMp_5_iter_847_EQ_15___d1848;
  tUInt8 DEF_toMp_cordToMp_4_iter_734_EQ_15___d1735;
  tUInt8 DEF_toMp_cordToMp_3_iter_621_EQ_15___d1622;
  tUInt8 DEF_toMp_cordToMp_2_iter_508_EQ_15___d1509;
  tUInt8 DEF_toMp_cordToMp_1_iter_395_EQ_15___d1396;
  tUInt8 DEF_toMp_cordToMp_0_iter_281_EQ_15___d1282;
  tUInt8 DEF_adjust_i_168_EQ_7___d2169;
  tUInt8 DEF_NOT_fromMp_cordFromMp_7_iter_906_EQ_15_907___d2908;
  tUInt8 DEF_NOT_fromMp_cordFromMp_6_iter_826_EQ_15_827___d2828;
  tUInt8 DEF_NOT_fromMp_cordFromMp_5_iter_746_EQ_15_747___d2748;
  tUInt8 DEF_NOT_fromMp_cordFromMp_4_iter_666_EQ_15_667___d2668;
  tUInt8 DEF_NOT_fromMp_cordFromMp_3_iter_586_EQ_15_587___d2588;
  tUInt8 DEF_NOT_fromMp_cordFromMp_2_iter_506_EQ_15_507___d2508;
  tUInt8 DEF_NOT_fromMp_cordFromMp_1_iter_426_EQ_15_427___d2428;
  tUInt8 DEF_NOT_fromMp_cordFromMp_0_iter_346_EQ_15_347___d2348;
  tUInt8 DEF_NOT_toMp_cordToMp_7_iter_073_EQ_15_074___d2075;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_7_infifo_first__023_BIT_6_ETC___d2058;
  tUInt8 DEF_NOT_toMp_cordToMp_6_iter_960_EQ_15_961___d1962;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_6_infifo_first__910_BIT_6_ETC___d1945;
  tUInt8 DEF_NOT_toMp_cordToMp_5_iter_847_EQ_15_848___d1849;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_5_infifo_first__797_BIT_6_ETC___d1832;
  tUInt8 DEF_NOT_toMp_cordToMp_4_iter_734_EQ_15_735___d1736;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_4_infifo_first__684_BIT_6_ETC___d1719;
  tUInt8 DEF_NOT_toMp_cordToMp_3_iter_621_EQ_15_622___d1623;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_3_infifo_first__571_BIT_6_ETC___d1606;
  tUInt8 DEF_NOT_toMp_cordToMp_2_iter_508_EQ_15_509___d1510;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_2_infifo_first__458_BIT_6_ETC___d1493;
  tUInt8 DEF_NOT_toMp_cordToMp_1_iter_395_EQ_15_396___d1397;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_1_infifo_first__345_BIT_6_ETC___d1380;
  tUInt8 DEF_NOT_toMp_cordToMp_0_iter_281_EQ_15_282___d1283;
  tUInt8 DEF_NOT_IF_toMp_cordToMp_0_infifo_first__231_BIT_6_ETC___d1266;
  tUInt8 DEF_NOT_adjust_i_168_EQ_7_169___d2170;
 
 /* Local definitions */
 private:
  tUWide DEF_ifft_fft_fft_stage_data_2___d3676;
  tUWide DEF_ifft_fft_fft_stage_data_1___d3327;
  tUWide DEF_ifft_fft_fft_stage_data_0___d2980;
  tUWide DEF_fft_fft_stage_data_2___d807;
  tUWide DEF_fft_fft_stage_data_1___d458;
  tUWide DEF_fft_fft_stage_data_0___d111;
  tUWide DEF_ifft_outfifo_first____d4301;
  tUWide DEF_ifft_fft_fft_outputFIFO_first____d4102;
  tUWide DEF_ifft_fft_fft_inputFIFO_first____d2978;
  tUWide DEF_fromMp_outfifo_first____d4285;
  tUWide DEF_fft_fft_outputFIFO_first____d4243;
  tUWide DEF_fft_fft_inputFIFO_first____d109;
  tUWide DEF_adjust_out_latch__h372646;
  tUWide DEF_adjust_in_latch__h370799;
  tUWide DEF_adjust_outputFIFO_first____d4273;
  tUWide DEF_toMp_outfifo_first____d4255;
  tUWide DEF_overlayer_infifo_first____d4145;
  tUWide DEF_overlayer_window__h737046;
  tUWide DEF_oversample_outfifo_first____d4205;
  tUWide DEF_oversample_window__h10267;
  tUWide DEF_ifft_fft_fft_stage_data_3_968_BITS_511_TO_0___d4098;
  tUWide DEF_fft_fft_stage_data_3_9_BITS_511_TO_0___d1229;
  tUWide DEF_oversample_window_8_BITS_127_TO_32___d89;
  tUWide DEF_ifft_fft_fft_stage_data_2_676_BIT_512_677_CONC_ETC___d4097;
  tUWide DEF_ifft_fft_fft_stage_data_2_676_BITS_447_TO_416__ETC___d4093;
  tUWide DEF_ifft_fft_fft_stage_data_1_327_BIT_512_328_CONC_ETC___d3675;
  tUWide DEF_ifft_fft_fft_stage_data_1_327_BITS_447_TO_416__ETC___d3671;
  tUWide DEF_ifft_fft_fft_stage_data_0_980_BIT_512_981_CONC_ETC___d3326;
  tUWide DEF_ifft_fft_fft_stage_data_0_980_BITS_447_TO_416__ETC___d3322;
  tUWide DEF_ifft_fft_fft_inputFIFO_notEmpty__961_CONCAT_if_ETC___d2979;
  tUWide DEF_fft_fft_stage_data_2_07_BIT_512_08_CONCAT_fft__ETC___d1228;
  tUWide DEF_fft_fft_stage_data_2_07_BITS_447_TO_416_09_MIN_ETC___d1224;
  tUWide DEF_fft_fft_stage_data_1_58_BIT_512_59_CONCAT_fft__ETC___d806;
  tUWide DEF_fft_fft_stage_data_1_58_BITS_447_TO_416_60_MIN_ETC___d802;
  tUWide DEF_fft_fft_stage_data_0_11_BIT_512_12_CONCAT_fft__ETC___d457;
  tUWide DEF_fft_fft_stage_data_0_11_BITS_447_TO_416_13_MIN_ETC___d453;
  tUWide DEF_fft_fft_inputFIFO_notEmpty__2_CONCAT_fft_fft_i_ETC___d110;
  tUWide DEF_fromMp_outfifo_first__285_BITS_511_TO_448_286__ETC___d4297;
  tUWide DEF_fromMp_outfifo_first__285_BITS_511_TO_448_286__ETC___d4294;
  tUWide DEF_oversample_outfifo_first__205_BITS_127_TO_112__ETC___d4225;
  tUWide DEF_oversample_outfifo_first__205_BITS_127_TO_112__ETC___d4220;
  tUWide DEF_fromMp_cordFromMp_7_outfifo_first__948_CONCAT__ETC___d2959;
  tUWide DEF_fromMp_cordFromMp_7_outfifo_first__948_CONCAT__ETC___d2956;
  tUWide DEF_ifft_fft_fft_outputFIFO_first__102_BITS_127_TO_ETC___d4141;
  tUWide DEF_ifft_fft_fft_outputFIFO_first__102_BITS_127_TO_ETC___d4131;
  tUWide DEF_ifft_fft_fft_stage_data_2_676_BITS_447_TO_416__ETC___d4087;
  tUWide DEF_ifft_fft_fft_stage_data_1_327_BITS_447_TO_416__ETC___d3665;
  tUWide DEF_ifft_fft_fft_stage_data_0_980_BITS_447_TO_416__ETC___d3316;
  tUWide DEF_fft_fft_stage_data_2_07_BITS_447_TO_416_09_MIN_ETC___d1218;
  tUWide DEF_fft_fft_stage_data_0_11_BITS_447_TO_416_13_MIN_ETC___d447;
  tUWide DEF_fft_fft_stage_data_1_58_BITS_447_TO_416_60_MIN_ETC___d796;
  tUWide DEF_toMp_cordToMp_7_outfifo_first__152_CONCAT_toMp_ETC___d2163;
  tUWide DEF_toMp_cordToMp_7_outfifo_first__152_CONCAT_toMp_ETC___d2160;
  tUWide DEF_IF_adjust_bin_166_BITS_18_TO_16_190_EQ_7_244_T_ETC___d2287;
  tUWide DEF_IF_adjust_bin_166_BITS_18_TO_16_190_EQ_7_244_T_ETC___d2282;
  tUWide DEF_fromMp_outfifo_first__285_BITS_511_TO_448_286__ETC___d4291;
  tUWide DEF_oversample_outfifo_first__205_BITS_127_TO_112__ETC___d4215;
  tUWide DEF_fromMp_cordFromMp_7_outfifo_first__948_CONCAT__ETC___d2953;
  tUWide DEF_ifft_fft_fft_outputFIFO_first__102_BITS_127_TO_ETC___d4121;
  tUWide DEF_ifft_fft_fft_stage_data_2_676_BITS_447_TO_416__ETC___d4001;
  tUWide DEF_ifft_fft_fft_stage_data_1_327_BITS_447_TO_416__ETC___d3579;
  tUWide DEF_ifft_fft_fft_stage_data_0_980_BITS_447_TO_416__ETC___d3230;
  tUWide DEF_fft_fft_stage_data_2_07_BITS_447_TO_416_09_MIN_ETC___d1132;
  tUWide DEF_fft_fft_stage_data_0_11_BITS_447_TO_416_13_MIN_ETC___d361;
  tUWide DEF_fft_fft_stage_data_1_58_BITS_447_TO_416_60_MIN_ETC___d710;
  tUWide DEF_toMp_cordToMp_7_outfifo_first__152_CONCAT_toMp_ETC___d2157;
  tUWide DEF_IF_adjust_bin_166_BITS_18_TO_16_190_EQ_7_244_T_ETC___d2277;
  tUWide DEF_fromMp_outfifo_first__285_BITS_511_TO_448_286__ETC___d4288;
  tUWide DEF_oversample_outfifo_first__205_BITS_127_TO_112__ETC___d4210;
  tUWide DEF_fromMp_cordFromMp_7_outfifo_first__948_CONCAT__ETC___d2950;
  tUWide DEF_ifft_fft_fft_outputFIFO_first__102_BITS_127_TO_ETC___d4111;
  tUWide DEF_toMp_cordToMp_7_outfifo_first__152_CONCAT_toMp_ETC___d2154;
  tUWide DEF_IF_adjust_bin_166_BITS_18_TO_16_190_EQ_7_244_T_ETC___d2272;
  tUWide DEF_overlayer_infifo_first__145_BITS_127_TO_112_14_ETC___d4178;
  tUWide DEF_overlayer_infifo_first__145_BITS_127_TO_112_14_ETC___d4169;
  tUWide DEF_ifft_outfifo_first__301_BITS_511_TO_496_302_CO_ETC___d4313;
  tUWide DEF_ifft_outfifo_first__301_BITS_511_TO_496_302_CO_ETC___d4310;
  tUWide DEF_oversample_infifo_first__7_CONCAT_oversample_w_ETC___d90;
 
 /* Rules */
 public:
  void RL_fir_mult();
  void RL_fir_add();
  void RL_chunker_iterate();
  void RL_oversample_shiftin();
  void RL_fft_fft_comb_fft();
  void RL_toMp_cordToMp_0_start();
  void RL_toMp_cordToMp_0_iterate();
  void RL_toMp_cordToMp_1_start();
  void RL_toMp_cordToMp_1_iterate();
  void RL_toMp_cordToMp_2_start();
  void RL_toMp_cordToMp_2_iterate();
  void RL_toMp_cordToMp_3_start();
  void RL_toMp_cordToMp_3_iterate();
  void RL_toMp_cordToMp_4_start();
  void RL_toMp_cordToMp_4_iterate();
  void RL_toMp_cordToMp_5_start();
  void RL_toMp_cordToMp_5_iterate();
  void RL_toMp_cordToMp_6_start();
  void RL_toMp_cordToMp_6_iterate();
  void RL_toMp_cordToMp_7_start();
  void RL_toMp_cordToMp_7_iterate();
  void RL_toMp_get_data();
  void RL_adjust_loop();
  void RL_adjust_loop_end();
  void RL_fromMp_cordFromMp_0_start();
  void RL_fromMp_cordFromMp_0_iterate();
  void RL_fromMp_cordFromMp_1_start();
  void RL_fromMp_cordFromMp_1_iterate();
  void RL_fromMp_cordFromMp_2_start();
  void RL_fromMp_cordFromMp_2_iterate();
  void RL_fromMp_cordFromMp_3_start();
  void RL_fromMp_cordFromMp_3_iterate();
  void RL_fromMp_cordFromMp_4_start();
  void RL_fromMp_cordFromMp_4_iterate();
  void RL_fromMp_cordFromMp_5_start();
  void RL_fromMp_cordFromMp_5_iterate();
  void RL_fromMp_cordFromMp_6_start();
  void RL_fromMp_cordFromMp_6_iterate();
  void RL_fromMp_cordFromMp_7_start();
  void RL_fromMp_cordFromMp_7_iterate();
  void RL_fromMp_get_data();
  void RL_ifft_fft_fft_comb_fft();
  void RL_ifft_inversify();
  void RL_overlayer_shiftout();
  void RL_splitter_iterate();
  void RL_fir_to_chunker();
  void RL_chunker_to_oversample();
  void RL_oversample_to_fft();
  void RL_fft_to_tomp();
  void RL_tomp_to_adjust();
  void RL_adjust_to_frommp();
  void RL_frommp_to_ifft();
  void RL_ifft_to_overlayer();
  void RL_overlayer_to_splitter();
 
 /* Methods */
 public:
  void METH_putSampleInput(tUInt32 ARG_putSampleInput_in);
  tUInt8 METH_RDY_putSampleInput();
  tUInt32 METH_getSampleOutput();
  tUInt8 METH_RDY_getSampleOutput();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkAudioPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkAudioPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkAudioPipeline &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkAudioPipeline &backing);
};

#endif /* ifndef __mkAudioPipeline_h__ */
